#!/bin/bash
set -eux

export DOCKER_BUILDKIT=1

docker build --build-arg DEBIAN_VERSION --build-arg RUBY_VERSION --target builder -t "public.ecr.aws/exapico/lambda-ruby-builder:$DEBIAN_VERSION-$RUBY_VERSION" .
docker build --build-arg DEBIAN_VERSION --build-arg RUBY_VERSION --target runtime -t "public.ecr.aws/exapico/lambda-ruby:$DEBIAN_VERSION-$RUBY_VERSION" .
